import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${manrope.className} dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>

        <main>{children}</main>

        <Footer></Footer>
      </body>
    </html>
  );
}
